server:
  port: 20001

spring:
  dubbo:
          application:
              name: consumer
          registry:
              address: zookeeper://10.3.5.45:7766
          scan: com.jzt.wechat.all.wechat.coupon.service
          server: true


logging:
  file: proxy.api.log