spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
        username: root
    dubbo:
        application:
            name: provider
        protocol:
            name: dubbo
            port: 2080
        registry:
            address: zookeeper://127.0.0.1:2181
        scan: com.jzt.platform.coupon.service
        server: true